### ISSUE TITLE
Categories not persisting correctly when added from Post screen.

### ISSUE THREAD

**Issue by 4imble** [rxtur/BlogEngine.NET#29]
##Potentially relevant background:
SQL Server persistance
MultiBlog

#Steps to reproduce
1) Go into admin
2) Click content, posts
3) Click existing post
4) Click + in the **RIGHT** hand menu for categories
5) Add a category

#Result
This category will not be in the database.
Attempting to delete this category will fail.
Attempting to save this post with this category will work but toast an error
Refreshing the app pool will result in the category disappearing.

#Expected Result
It should persist in the same way that it does when you add a category via the LEFT menu under Content / Categories

**Comment by rxtur** [comment]
Is this DB related? I just did this in test site (http://zoo.azurewebsites.net) which uses XML provider and it seems to work as expected.

**Comment by 4imble** [comment]
Yes I am using SQL server. I am pretty sure its related to this persistence
type.

**Comment by rxtur** [comment]
Actually, I don't have this issue with SQL Server either - followed your steps, all worked fine. Did you upgrade? I used fresh install to test.

**Comment by 4imble** [comment]
This was a fresh install. I will try and reproduce on my home machine
tomorrow.

**Comment by 4imble** [comment]
I just tried this on another machine and I had the same problem. I used the ready published version of the blog, rather than getting the code and publishing my own.

**Comment by rxtur** [comment]
Not able to recreate this.

**Comment by iGanja** [comment]
I have this exact same issue at this time.
I am using version 3.3.5, and am running from the source code version.
I do not know if this has been fixed in some other area in the Core, but my fix was to fix the call from the angular controller used by the widget (posteditorController.js) which did NOT initialize $scope.category to { "IsChecked": false, "Id": null, "Parent": null, "Title": "", "Description": "", "Count": 0 }; as categoryContoller.js does. Instead it would only set $scope.category values as the bound fields were updated in the UI. Hence a saveCategory() call might send a payload to the api controller of {Title: "newTitle"} without all the other properties set to default values. This call would return a success from the api service, but would NOT update the database.
Hope this helps someone.
