### ISSUE TITLE
Found few issues on BlogEngine

### ISSUE THREAD

**Issue by arjunans** [rxtur/BlogEngine.NET#85]
Hi 

I have downloaded the latest code and run the project. I have found couple of issues on the new build

1. News posts added in the BlogEngine is not reflecting in the post list widget.

2. URL is not changing after modifying the title of the post.

3. Unpublishing any exisitng articles are not reflecting on the page until admin logs off. Articles are keep displaying in the page even though it is unpublished.

4. News posts are not reflecting in the rss feeds.

**Comment by sqc1999** [comment]
The third one is not an issue, admin can see posts even they are not published yet.

**Comment by rfaix** [comment]
That is a big issue because only the admin can see new posts and unpublished posts. No one else can see the posts which are getting announced by the newsletter!!!

**Comment by sqc1999** [comment]
@rfaix So it is not good to unpublish a post or change its URL. It is like an API breaking change in some library.

**Comment by rxtur** [comment]
#4 seems to be a duplicate issue, others not issues.
And please don't put multiple issues together, one per page with clear steps to reproduce and expected/actual results so it is easier to reproduce and fix.

**Comment by rfaix** [comment]
@sqc1999, the issue is the incorrect handling of the posting data and not publishing and unpublishing. My server is located in another timezone (time difference 6/7 hours). The publishing date is used from the client and the server shows the content on his local time. The problem would be fixed if the script is using the server time and not this from the client.
