### ISSUE TITLE
incorrect title in TAG page

### ISSUE THREAD

**Issue by HAndy2013** [rxtur/BlogEngine.NET#89]
e.g.
I hava a tag named '**_asp.net远程部署_**', but the **title element** in tag page is ==>[所有加标签的文章 '**_sp.net远程部署_**'].
the first char of the tag is lost...

**Comment by sqc1999** [comment]
@rxtur Why did you simply closed this issue? I used to expereniced the problem and managed to solve it by remove a SubString(1) call somewhere(sorry I can't remember the exact position, I made the change a long time ago). I'm not sure if it has been fixed, but at least could you please give some explanation?

**Comment by sqc1999** [comment]
@rxtur I've found it. Could you please see [this](https://github.com/rxtur/BlogEngine.NET/blob/a34f214fa0754afa8171bd5c88c9e320dc554b4a/BlogEngine/BlogEngine.NET/default.aspx.cs#L256)?
I could not understand the purpose of the call to `Substring` in this line very well. And it seems that this call throws away the first character of the tag name and caused the problem.
I hope you can reopen this issue because it actually exists.

**Comment by rxtur** [comment]
Wasn't intentional, either I pushed wrong button or Github chocked.

**Comment by rxtur** [comment]
Should be fixed with 3.3.0.5
